= Related Work

This chapter reviews work that motivates the modeling-tool usability, collaboration awareness, educational integration, and compatibility concerns addressed in this thesis. It distinguishes editor interaction, which determines how users create and revise diagrams, from the integration concerns that arise when diagrams move through educational and downstream workflows. The review therefore focuses on modeling-tool usability, collaboration awareness, and the positioning of Apollon as part of an educational modeling ecosystem.

== Usability of Modeling Tools

Ternes, Rosenthal, and Strecker reviewed 72 publications on user interface design for modeling tools and identified graphical editing, layout, navigation, and feedback as recurring research areas @ternes2021ui. Their review shows that modeling-tool usability is not limited to the final diagram. It also concerns the effort required to create, revise, inspect, and maintain models with the editor mechanisms provided by a tool @ternes2021ui.

Planas and Cabot observed students creating UML class diagrams with MagicDraw and Papyrus and analyzed modeling obstacles, modeling effort, and editor support @planas2020uml. Their study is relevant because repeated student modeling workflows are affected by small interaction costs: reconnecting relations, correcting layout, finding diagram content, and recovering from accidental or unclear editor behavior. For Apollon, these concerns motivate the focus on edge manipulation, alignment support, navigation, and predictable editing controls without claiming a controlled quantitative usability improvement.

UML diagramming tools also need to fit teaching environments. Lu and Alexandru review UML diagramming software for higher education courses and discuss tool characteristics relevant to educational use @lu2023umltools. This supports treating Apollon not only as a drawing surface, but as an educational modeling tool used repeatedly by students and instructors. Usability improvements therefore need to support individual modeling, instructor preparation, assessment-related workflows, and reuse across the surrounding learning ecosystem.

== Collaborative Diagram Editors

General-purpose editors provide practical reference points for common collaboration behavior. draw.io documents collaborator cursors and selections during concurrent editing.#footnote[draw.io, "Collaborate in real time using draw.io": #link("https://www.drawio.com/docs/manual/collaboration/concurrent-editing/")[www.drawio.com/docs/manual/collaboration/concurrent-editing].] Lucid documents collaborator cursors and a function for following another participant's canvas view.#footnote[Lucid, "Collaborate in Lucid": #link("https://help.lucid.co/hc/en-us/articles/13893815605268-Collaborate-in-Lucid")[help.lucid.co/hc/en-us/articles/13893815605268-Collaborate-in-Lucid].] These product examples show familiar interaction patterns, but they are not used here as academic evidence for collaboration design.

The scholarly grounding for this part of the thesis is workspace awareness. Gutwin and Greenberg describe workspace awareness as knowledge about the interaction of others with a shared workspace, including who is present, where they are working, and what they are doing @gutwin2002workspace. For collaborative modeling, this means that synchronized diagram data alone is insufficient. Users also need collaboration awareness about other users' activity, location, selections, and focus in the shared diagram.

This directly connects to Apollon's collaboration-awareness cues. In Artemis team modeling, they help students coordinate work in a shared modeling session within an interactive learning context @krusche2018artemis, while standalone use benefits from the same concepts. Awareness data describes the current session and should not be coupled to the persisted diagram model, which must remain usable in later educational, feedback, export, and editing workflows.

== Positioning of This Thesis

The reviewed work motivates individual concerns addressed by this thesis, while the thesis applies them in the specific integration context of Apollon. Modeling-tool usability research motivates attention to editing effort, navigation, layout support, and repeated modeling workflows @ternes2021ui @planas2020uml. UML tool research in higher education motivates considering Apollon as part of teaching and learning workflows rather than as an isolated editor @lu2023umltools. Workspace-awareness research motivates collaboration awareness that communicates activity, location, selection, and focus in a shared workspace @gutwin2002workspace.

The contribution is therefore positioned as a system-level improvement of an educational modeling ecosystem rather than as a controlled usability experiment. It applies the reviewed work to reusable editor interactions, collaboration awareness across standalone and embedded contexts, and compatibility of educational and downstream workflows. This positioning connects the literature to Chapters 4 to 6, where integration and reuse are treated as central constraints.
