= Related Work

This chapter reviews work that motivates the usability, visual clarity, collaboration awareness, educational integration, and ecosystem compatibility concerns addressed in this thesis. It distinguishes four related concerns: notation semantics, visual representation, editor interaction, and ecosystem integration. Notation semantics define the meaning of diagram elements and relationships. Visual representation determines how those elements are perceived. Editor interaction determines how users create, revise, navigate, and export diagrams. Ecosystem integration determines how diagrams move between standalone use, learning platforms, feedback systems, assessment workflows, and development tools.

The thesis does not introduce a new notation. It improves how existing educational diagrams are edited, shared, exported, and integrated while preserving the semantics of the supported diagram types. The review therefore focuses on modeling-tool usability, cognitive effectiveness of visual representations, collaboration awareness, and the positioning of Apollon as part of an educational modeling ecosystem.

== Usability of Modeling Tools

Ternes, Rosenthal, and Strecker reviewed 72 publications on user interface design for modeling tools and identified graphical editing, layout, navigation, and feedback as recurring research areas @ternes2021ui. Their review shows that modeling-tool usability is not limited to the final diagram. It also concerns the effort required to create, revise, inspect, and maintain models with the editor mechanisms provided by a tool @ternes2021ui.

Planas and Cabot observed students creating UML class diagrams with MagicDraw and Papyrus and analyzed modeling obstacles, modeling effort, and editor support @planas2020uml. Their study is relevant because repeated student modeling workflows are affected by small interaction costs: reconnecting relations, correcting layout, finding diagram content, and recovering from accidental or unclear editor behavior. For Apollon, these concerns motivate the focus on edge manipulation, alignment support, navigation, and predictable editing controls without claiming a controlled quantitative usability improvement.

UML diagramming tools also need to fit teaching environments. Lu and Alexandru review UML diagramming software for higher education courses and discuss tool characteristics relevant to educational use @lu2023umltools. This supports treating Apollon not only as a drawing surface, but as an educational modeling tool used repeatedly by students and instructors. Usability improvements therefore need to support individual modeling, instructor preparation, assessment-related workflows, and reuse across the surrounding learning ecosystem.

== Cognitive Effectiveness of Visual Notations

Green and Petre introduced cognitive dimensions as a framework for evaluating visual programming environments. Dimensions such as viscosity, visibility, error-proneness, and hard mental operations describe how an environment supports modification and comprehension @green1996cognitive. These dimensions are useful for separating notation design from editor and rendering behavior. Apollon can preserve established UML and educational diagram semantics while still reducing local editing resistance, making relevant information easier to see, and avoiding editor behavior that increases the likelihood of mistakes.

Moody's Physics of Notations defines principles for cognitively effective visual notations, including perceptual discriminability, complexity management, and cognitive integration @moody2009physics. In this thesis, these principles motivate visual clarity concerns around labels, crossings, visual distinctions between diagram elements, and exported representations. The contribution is not a redesign of UML or the creation of a new visual language. Instead, it concerns editor and rendering behavior that helps preserve the visual distinctions of existing notations during editing and export, especially when diagrams grow or are used outside the editor.

== Collaborative Diagram Editors

General-purpose editors provide practical reference points for common collaboration behavior. draw.io documents collaborator cursors and selections during concurrent editing.#footnote[draw.io, "Collaborate in real time using draw.io": #link("https://www.drawio.com/docs/manual/collaboration/concurrent-editing/")[www.drawio.com/docs/manual/collaboration/concurrent-editing].] Lucid documents collaborator cursors and a function for following another participant's canvas view.#footnote[Lucid, "Collaborate in Lucid": #link("https://help.lucid.co/hc/en-us/articles/13893815605268-Collaborate-in-Lucid")[help.lucid.co/hc/en-us/articles/13893815605268-Collaborate-in-Lucid].] These product examples show familiar interaction patterns, but they are not used here as academic evidence for collaboration design.

The scholarly grounding for this part of the thesis is workspace awareness. Gutwin and Greenberg describe workspace awareness as knowledge about the interaction of others with a shared workspace, including who is present, where they are working, and what they are doing @gutwin2002workspace. For collaborative modeling, this means that synchronized diagram data alone is insufficient. Users also need collaboration awareness about other users' activity, location, selections, and focus in the shared diagram.

This directly connects to Apollon's live cursors, participant names, selections, and viewport following. In Artemis team modeling, these cues help students coordinate work in a shared modeling session within an interactive learning context @krusche2018artemis, while standalone use benefits from the same collaboration awareness concepts. At the same time, cursors, selections, participant identity, and followed viewport state are transient collaboration state. They describe the current session and should not be coupled to the persisted diagram model, which must remain usable for quiz generation, assessment, Athena feedback, export, and later editing.

== Positioning of This Thesis

The reviewed work motivates individual concerns addressed by this thesis, while the thesis applies them in the specific integration context of Apollon. Modeling-tool usability research motivates attention to editing effort, navigation, layout support, and repeated modeling workflows @ternes2021ui @planas2020uml. UML tool research in higher education motivates considering Apollon as part of teaching and learning workflows rather than as an isolated editor @lu2023umltools. Cognitive notation research motivates preserving visual distinctions, labels, crossings, and readable exported representations without changing the underlying notation @green1996cognitive @moody2009physics. Workspace-awareness research motivates collaboration awareness that communicates activity, location, selection, and focus in a shared workspace @gutwin2002workspace.

The contribution is therefore positioned as a system-level improvement of an educational modeling ecosystem rather than as a new notation or a controlled usability experiment. It improves editor interaction and visual export while preserving existing notations, supports collaboration awareness in standalone shared modeling and Artemis team modeling contexts, and maintains compatibility with Artemis, Athena, iOS, VS Code, quiz, assessment, and export workflows. This positioning connects the literature reviewed here to the requirements, architecture, and implementation work in Chapters 4 to 6, where integration and reuse are treated as central constraints of the thesis.
