= Summary <summary-chapter>

== Status

This thesis improved Apollon as an educational modeling ecosystem rather than as a single editor instance. The implemented work addressed the Apollon library, the standalone web application, the standalone home page, the mobile/iOS application, Artemis, Athena, and the VS Code extension. Across these environments, the work aimed to reduce friction during diagram creation, make collaboration awareness reusable, preserve educational workflows, and produce more dependable visual exports and export artifacts.

The work followed an iterative development process. Requirements were refined while features were implemented, integrated, tested, and discussed through qualitative feedback. This process was important because Apollon is reused in several host contexts: a change in the editor can affect standalone shared modeling, Artemis team modeling, mobile export, quiz generation, assessment views, Athena feedback workflows, and IDE-based editing. The final state is therefore best understood as a coordinated set of ecosystem improvements with remaining product directions, not as a single isolated feature release.

=== Realized Goals

The first objective was to improve modeling and application usability. This was addressed through changes that reduced repeated editing effort and made common workflows easier to finish. Edge bending, waypoint dragging, reconnection, dynamic handles, line jumps, and label readability fixes improved direct manipulation and visual clarity for relationships between diagram elements. Alignment guides, keyboard deletion, class member reordering, scroll lock, and editor-side user interface cleanup addressed smaller sources of friction that accumulate during repeated modeling. The standalone home page and routing work gave users clearer paths for creating, reopening, and sharing local and shared diagrams, while mobile/iOS export support made diagram export less dependent on desktop browser assumptions.

The second objective was to support collaborative modeling. The thesis introduced live cursors, presence information, visible selections, and viewport following so that collaborators can better understand where others are working during a shared session. These awareness features were moved into the Apollon library after their standalone use, which allowed reuse in both standalone shared modeling and Artemis team modeling. The implementation also preserved an important boundary: cursors, presence, selections, and followed viewports are transient collaboration state, while the persisted diagram model remains focused on the diagram itself.

The third objective was to integrate Apollon into educational systems. The work migrated Artemis to the maintained Apollon integration while preserving modeling exercises, quiz-related editor interactions, assessment views, and team modeling. Drag-and-drop quiz generation was repaired for the maintained Apollon model format, nested selections were supported, and assessment compatibility was strengthened where serialization changes affected grading behavior. Athena support was updated so feedback workflows can consume earlier and current serialized Apollon models required during the migration period. The VS Code extension was also migrated to the maintained Apollon renderer and version, reducing fragmentation across the ecosystem. These changes kept host responsibilities clear: Artemis owns courses, users, permissions, persistence, submissions, quiz data, and assessment records, while Athena consumes serialized Apollon models for feedback generation.

The fourth objective was to improve diagram portability. The thesis provided a server-side PDF export path, improved SVG export compatibility, and addressed rendering issues involving text bounds, clipping, labels, and diagram-specific shapes. Visual export checks supported this work by making rendering regressions easier to detect. The result is a more dependable basis for producing derived export artifacts from persisted diagram models. At the same time, the work does not claim universal interoperability. It improves the export and rendering paths used by the Apollon ecosystem while leaving additional format and conversion guarantees to later work.

=== Remaining Limitations

Several remaining limitations concern edge interaction and diagram layout. Qualitative feedback indicated that users still expect easier straight-line creation, more flexible anchor behavior, larger selectable areas, and stronger snapping support. The implemented edge work improved direct manipulation and readability, but it did not remove all layout correction effort. Further refinement is needed for proportional connection points, clearer affordances for selecting edge segments, and predictable behavior when diagrams become dense.

Persistence, ownership, and long-term project workflows also remain open product directions. The standalone home page distinguishes local and shared diagrams, but optional login, persistent shared diagrams, stronger ownership, local file-system integration, PWA support, and Git-friendly workflows require broader product and architectural decisions. These topics involve authentication, authorization, access control, storage ownership, and long-term collaboration behavior. They therefore go beyond editor-level improvements in the Apollon library.

Educational workflows show a similar pattern. The thesis preserved and repaired important Artemis, Athena, and VS Code workflows, but feedback still identified review comments, assessment-oriented collaboration, PlantUML import and export, broader UML notation support, and tutorials as future needs. Static and abstract class members, type parameters, directed relationships, and additional notation details would make Apollon more useful in teaching contexts, but they require careful design so that beginner workflows remain approachable.

Advanced editor functionality and export hardening remain further limitations. Users requested multiline text, stereotypes, color customization, layers, command palettes, and code generation. These features could support instructors, researchers, and experienced users, but they should not overload the main educational editing flow. Export and rendering can also be hardened further, especially where editable model exchange, print-oriented formats, and external tools place different expectations on serialized Apollon models and derived export artifacts.

== Conclusion

The thesis strengthened Apollon as a reusable educational modeling ecosystem. User-facing modeling improvements matter because the same editor behavior appears in the standalone web application, the mobile/iOS application, Artemis, and the VS Code extension. Reducing editing friction, improving collaboration awareness, and making exports more dependable therefore benefits more than one interface. The work also showed that usability and integration are connected: an editor feature becomes more valuable when it can be reused consistently across the environments in which students, instructors, assessors, and standalone users work.

The architectural separation between shared editor behavior and host-owned workflows was central to this result. Editor, model, rendering, callback, and collaboration-awareness behavior could be placed in the Apollon library, while Artemis, Athena, the standalone application, the mobile/iOS application, and the VS Code extension kept their own responsibilities. This separation preserved Artemis and Athena workflows while allowing the maintained Apollon version to replace legacy behavior in important contexts. Qualitative feedback indicated that the implemented direction addresses relevant workflows, but it does not replace a controlled usability study and does not imply that all usability problems are solved.

== Future Work

Future work should continue editor usability and notation support. Edge and layout refinement should focus on straight-line creation, snapping, anchor behavior, selectable areas, and clearer visual affordances. Notation work should address broader UML support, multiline text, stereotypes, color customization, layers, and tutorials without making the primary student workflow harder to learn.

Collaboration, persistence, ownership, and review workflows form a second direction. Persistent shared diagrams, optional login, stronger ownership semantics, review comments, and assessment-oriented collaboration would make Apollon more useful for supervision and long-term teaching work. These features should preserve the boundary between reusable collaboration awareness in the Apollon library and host-specific collaboration transport, persistence, authentication, authorization, and access-control policies.

Educational and development ecosystem integration should also continue. Artemis workflows can benefit from deeper review and assessment support, while Athena compatibility should keep focusing on serialized Apollon models required by feedback workflows. PlantUML import and export, Git-friendly project workflows, local file-system integration, PWA support, and VS Code extension continuity would connect Apollon more closely to teaching, documentation, and development practices.

Finally, export and portability should be hardened further. Future work should distinguish editable model exchange from visual exports such as SVG, PNG, PDF, and presentation formats, and should continue improving deterministic rendering, text bounds, clipping behavior, and compatibility with external tools. The central architectural boundary should remain intact: reusable editor, model, rendering, callback, and collaboration-awareness behavior belongs in the Apollon library, while host-specific persistence, authentication, authorization, collaboration transport, course workflows, submissions, assessment records, and deployment stay outside the library.
